# This workflow will run tests using node, bump the version and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test

  package-publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
       with:
        always-auth: true
        node-version: 14.x
        registry-url: https://npm.pkg.github.com/
        scope: "@iamnotaturtle"
     - run: echo "registry=https://npm.pkg.github.com/@iamnotaturtle" >> .npmrc
     - run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
     - run: yarn install --frozen-lockfile
     - run: yarn version --prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
     - run: yarn pack
     - run: npm publish $(ls *.tgz)
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
